const assert = require('assert')
const { part1, part2 } = require('./script')

const data = 
`.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

describe('Day 7: Laboratories', () => {
    describe('Part One', () => {
        it('Should find how many times the beam will split', () => {
            assert.strictEqual(part1(data), 21)
        })
    })

    describe('Part Two', () => {
        it('Should find how many different timelines a single tachyon particle will end up on', () => {
            assert.strictEqual(part2(data), 40)
        })
    })
})

