const assert = require('assert')
const { part1, part2, getNextSecret } = require('./script')

const data = 
`1
10
100
2024`

describe('Day 22: Monkey Market', () => {
    describe('getNextSecret', () => {
        it('should get the next secret', () => {
            assert.strictEqual(getNextSecret(123n), 15887950n)
            assert.strictEqual(getNextSecret(15887950n), 16495136n)
        })
    })
    describe('Part One', () => {
        it('should give the sum of the 2000th secret number generated by each buyer', () => {
            assert.strictEqual(part1(data), 37327623)
        })
    })

    describe('Part Two', () => {
        it('should calculate the most bananas you can get', () => {
            // assert.strictEqual(part2(data), data)
        })
    })
})

